### ISSUE TITLE
Facing Issue when i upload my livehosting (using HestiaCP)

### ISSUE THREAD

**Issue by techandtips86** [rail5/SimpleFS#1]
At first I uploaded this code on Xampp, This is working perfectly, But after testing xampp when I uploaded my live hosting for personal use (Basically I am using HestiaCP) then I am facing an issue. I saw after creating a user that when I put it on the signin form it then shows 500 errors. Please help me. I am very new to Linux.

**Comment by rail5** [comment]
I'm adding the extra information you sent me over email here:

With PHP set to display errors:
```
PHP Fatal error:  Uncaught PDOException: could not
find driver in [...]/public_html/functions.global.php:18
Stack trace:
#0
[...]/public_html/functions.global.php(18):
PDO->__construct()
#1 [...]public_html/manage.php(16): contactDB()
#2 {main}

thrown in [..]/public_html/functions.global.php
on line 18'
```

SimpleFS creates a SQLite file database to keep track of uploaded files -- it looks like you don't have the SQLite module installed for PHP

You say you're on Linux -- if you have shell/SSH access, you should be able to install the module by running the command `sudo apt install php-sqlite3` and then re-starting your web server

I think it might be a good idea to add these checks to **setup.php**. I'll update setup.php to have it check that all the necessary PHP modules are installed & to provide a warning if they're not

**Comment by techandtips86** [comment]
Sir,
Just I install SQLite using sudo apt install php-sqlite3
but show install successfully.

but give me error message again.

**Comment by rail5** [comment]
Did you restart your server after installing?

If so, can you create a PHP file on your web server with the following code:
```
<?php
print_r(implode(', ', get_loaded_extensions()));
```
And paste the output here?

The output should show `Core, date, ...` etc. We're looking for "pdo_sqlite"

**Comment by techandtips86** [comment]
Yes Sir, I restarted, But after that I got a solution from a Hestia CP blog. 
Then i use " **apt-get install php8.1-sqlite3 php8.0-sqlite3 php7.4-sqlite3 -y**" code then it runs perfectly run.
Thank you very much sir. Many many thanks your proper reply and support me. Because of I am new learner on Linux and I will use it for personals purpose.
One more thing Sir can you share me a corn job command line to auto delete file for X time. I made it but all files have been deleted but in manage pages showting all files and also downloaded. I am confuse from where file is downloading. because of in the Files Folde there is no files.

**Comment by rail5** [comment]
You don't have to call me 'sir,' lol, but I appreciate the politeness

SimpleFS stores (1) a file and (2) a record of the file in the SQLite database -- even after you delete the file, if you don't delete the record from the SQLite database, SimpleFS will think that the file is still there.

If you delete the file from **manage.php** then it handles both the file and the SQLite database

An option to automatically delete files after a certain time is not a bad idea for a feature, though. I'm going to close this issue as completed, and open a new one to start trying to implement that feature.
