### ISSUE TITLE
Please share or update file to do delete all files after a certain time like Wetransfer.

### ISSUE THREAD

**Issue by techandtips86** [rail5/SimpleFS#3]
Sir,
Please share or update file to do delete all files after a certain time like We transfer.
I am trying to a cron job setup, but i cant do, So if you please give me a command line for corn job it will better for me. Although it is very bountiful.

One more thing if possible pls add one feature on it this is mail function. Automatically send mail for sharing file.

**Comment by rail5** [comment]
An auto-delete feature has now been added. I would recommend deleting your installation of SimpleFS & downloading the latest version (2.0)

Thank you for the great suggestion!

**Comment by techandtips86** [comment]
> An auto-delete feature has now been added. I would recommend deleting your installation of SimpleFS & downloading the latest version (2.0)
> 
> I followed setup file is being deleted after first time. But I am saying delete upload file after a certain time. It is also developed sir.

**Comment by rail5** [comment]
Yes, that's what was added for version 2. The "auto-delete" time can be set in **manage.php**

Here's a screenshot:

![](https://raw.githubusercontent.com/rail5/SimpleFS/main/screen-manage.png)

**Comment by techandtips86** [comment]
Sir it can be global. I mean just setup a time first then this time set auto matically delete. Like as wetransfer. One more thing please can you add email options to share file.

**Comment by rail5** [comment]
The setting in manage.php is global (meaning that it applies to all files uploaded by the user); I've never used WeTransfer so I'm not sure what you mean
