### ISSUE TITLE
Copy Link Button not working (not Clickable) text field also not enable.

### ISSUE THREAD

**Issue by techandtips86** [rail5/SimpleFS#7]
Sir,
Today I tried your new version 2.1. but it has bugs.
1. Copy button not working
2. Copy link text area not enable
3. Please smaller case in copy link text field.
4. Please enable Drag and Drop facilities on upload page.
5. Your Auto Delete function works perfectly.
6. Try to enable this function only for admin (who can change password)

**Comment by rail5** [comment]
The button & the text field are working on Firefox & Chromium on Linux, but I tested from Firefox on Windows earlier today and found the same problem as you. I'll look into it

**Comment by techandtips86** [comment]
> The button & the text field are working on Firefox & Chromium on Linux, but I tested from Firefox on Windows earlier today and found the same problem as you. I'll look into it

Thank. you for your quick reply. One more thing you can add one option to setup page
1. Change Name and title option (user can change name and title)
2. Upload a FabIcon option. (user can upload a good favicon)
