### ISSUE TITLE
New Bugs

### ISSUE THREAD

**Issue by techandtips86** [rail5/SimpleFS#8]
Just now i follow that when i upload single pdf file then when i am downloading then file name extension has been change.
For example. my original file name is "Orchid.pdf" but when its downloaded name changed with "orchid.pdf.html" after download you have to edit again this file extension.

**Comment by rail5** [comment]
I can't replicate this bug; it seems to be working fine on all my browsers on both Linux & Windows for me.

I've issued a potential patch. Try downloading the [latest download.php](https://raw.githubusercontent.com/rail5/SimpleFS/main/download.php) and replacing your **download.php**, and tell me if that fixes it

**Comment by techandtips86** [comment]
> I can't replicate this bug; it seems to be working fine on all my browsers on both Linux & Windows for me.
> 
> I've issued a potential patch. Try downloading the [latest download.php](https://raw.githubusercontent.com/rail5/SimpleFS/main/download.php) and replacing your **download.php**, and tell me if that fixes it

Just i replace code but right now shows 502 error.

you just check my link : https://share.livetv.ml
![Screen Shot 2023-04-27 at 12 46 18 PM](https://user-images.githubusercontent.com/127884368/234789109-f90c9919-7c04-4cb8-8009-ee42539dec09.png)

user : admin pass : admin

**Comment by rail5** [comment]
These are some very strange errors.

Can you run a test for me? Can you edit **download.php** and look for these **five** lines of code:

```
header("Cache-Control: public");
header("Pragma: public");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Cache-Control: public");
```

And comment them out by putting `//` before them, like this:

```
// header("Cache-Control: public");
// header("Pragma: public");
// header("Expires: 0");
// header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
// header("Cache-Control: public");
```

And see if that changes anything?

Everything is working fine on my servers, so I can't run the test myself

**Comment by techandtips86** [comment]
> These are some very strange errors.
> 
> Can you run a test for me? Can you edit **download.php** and look for these **five** lines of code:
> 
> ```
> header("Cache-Control: public");
> header("Pragma: public");
> header("Expires: 0");
> header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
> header("Cache-Control: public");
> ```
> 
> And comment them out by putting `//` before them, like this:
> 
> ```
> // header("Cache-Control: public");
> // header("Pragma: public");
> // header("Expires: 0");
> // header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
> // header("Cache-Control: public");
> ```
> 
> And see if that changes anything?
> 
> Everything is working fine on my servers, so I can't run the test myself

i Just change but same error.
![Screen Shot 2023-04-27 at 12 59 30 PM](https://user-images.githubusercontent.com/127884368/234791414-053871b4-2071-4659-b66d-56e135b0f2b7.png)

**Comment by rail5** [comment]
Try also commenting out:

```
// ob_clean();
// ob_end_flush();
```

**Comment by techandtips86** [comment]
> Try also commenting out:
> 
> ```
> // ob_clean();
> // ob_end_flush();
> ```

where is this code?

**Comment by rail5** [comment]
> where is this code?

Just above the other five lines you already commented out in download.php

**Comment by techandtips86** [comment]
> > where is this code?
> 
> Just above the other five lines you already commented out in download.php

same error shows

**Comment by techandtips86** [comment]
if you need i can share my screen via any desk

**Comment by rail5** [comment]
One final test:

Try changing this whole section in download.php:

```
ob_clean();
ob_end_flush();
header("Cache-Control: public");
header("Pragma: public");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Cache-Control: public");
header('Content-Type: application/octet-stream');
header("Content-Transfer-Encoding: Binary");
header("Content-disposition: attachment; filename=\"" .$fileName. "\""); 
header("Content-length: " . filesize($filename)); 
readfile($fetched[0]); 
exit(0);
```

To just this:

```
header('Content-Type: application/octet-stream');
header("Content-Transfer-Encoding: Binary");
header("Content-disposition: attachment; filename=\"" .$fileName. "\""); 
readfile($fetched[0]); 
```

**Comment by techandtips86** [comment]
> 
![Screen Shot 2023-04-27 at 12 59 30 PM](https://user-images.githubusercontent.com/127884368/234792935-4c306a5b-f47f-438b-84fd-f4c6c1ade91f.png)

**Comment by techandtips86** [comment]
> One final test:
> 
> Try changing this whole section in download.php:
> 
> ```
> ob_clean();
> ob_end_flush();
> header("Cache-Control: public");
> header("Pragma: public");
> header("Expires: 0");
> header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
> header("Cache-Control: public");
> header('Content-Type: application/octet-stream');
> header("Content-Transfer-Encoding: Binary");
> header("Content-disposition: attachment; filename=\"" .$fileName. "\""); 
> header("Content-length: " . filesize($filename)); 
> readfile($fetched[0]); 
> exit(0);
> ```
> 
> To just this:
> 
> ```
> header('Content-Type: application/octet-stream');
> header("Content-Transfer-Encoding: Binary");
> header("Content-disposition: attachment; filename=\"" .$fileName. "\""); 
> readfile($fetched[0]); 
> ```

Right now it is perfectly working.... Thank you sir.

**Comment by techandtips86** [comment]
> > One final test:
> > Try changing this whole section in download.php:
> > ```
> > ob_clean();
> > ob_end_flush();
> > header("Cache-Control: public");
> > header("Pragma: public");
> > header("Expires: 0");
> > header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
> > header("Cache-Control: public");
> > header('Content-Type: application/octet-stream');
> > header("Content-Transfer-Encoding: Binary");
> > header("Content-disposition: attachment; filename=\"" .$fileName. "\""); 
> > header("Content-length: " . filesize($filename)); 
> > readfile($fetched[0]); 
> > exit(0);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To just this:
> > ```
> > header('Content-Type: application/octet-stream');
> > header("Content-Transfer-Encoding: Binary");
> > header("Content-disposition: attachment; filename=\"" .$fileName. "\""); 
> > readfile($fetched[0]); 
> > ```
> 
> Right now it is perfectly working.... Thank you sir.

please update this download.php file on your server
